// Wails runtime API for communicating with Go backend
// This will be auto-generated by Wails in production builds

// Check if running under Wails
export const wailsAvailable = typeof window !== 'undefined' && window.go !== undefined

function fileUriToFsPath(uri) {
  try {
    const u = new URL(uri)
    if (u.protocol === 'file:') {
      // URL pathname on Windows starts with "/C:/..." — strip the leading slash
      return decodeURIComponent(u.pathname.replace(/^\//, ''))
    }
  } catch { }
  if (typeof uri === 'string' && uri.startsWith('file://')) {
    return decodeURIComponent(uri.replace(/^file:\/\//, ''))
  }
  return uri
}

export async function resolveMediaSrc(uri) {
  try {
    const p = fileUriToFsPath(String(uri || ''))
    if (!p) return null

    // In Wails, use the wails runtime to convert file paths
    if (wailsAvailable) {
      // Files are served directly via the asset server
      return `file://${p}`
    }

    // Fallback: check if Tauri is available
    // (Tauri support removed)

    return String(uri || '')
  } catch (e) {
    // Fallback to original URI
    return String(uri || '')
  }
}

// Wails Go backend methods
// These will be generated by Wails and available at window.go.main.App.<method>
export async function applyProject(addr, json) {
  if (!wailsAvailable) {
    throw new Error('Wails runtime is not available')
  }
  try {
    const result = await window.go.main.App.ApplyProject(addr, json)
    return result
  } catch (e) {
    throw new Error(`ApplyProject failed: ${e}`)
  }
}

export async function play(addr, at = null) {
  if (!wailsAvailable) {
    throw new Error('Wails runtime is not available')
  }
  try {
    const result = await window.go.main.App.Play(addr, at)
    return result
  } catch (e) {
    throw new Error(`Play failed: ${e}`)
  }
}

export async function pause(addr) {
  if (!wailsAvailable) {
    throw new Error('Wails runtime is not available')
  }
  try {
    const result = await window.go.main.App.Pause(addr)
    return result
  } catch (e) {
    throw new Error(`Pause failed: ${e}`)
  }
}

export async function stop(addr) {
  if (!wailsAvailable) {
    throw new Error('Wails runtime is not available')
  }
  try {
    const result = await window.go.main.App.Stop(addr)
    return result
  } catch (e) {
    throw new Error(`Stop failed: ${e}`)
  }
}

export async function seek(addr, to) {
  if (!wailsAvailable) {
    throw new Error('Wails runtime is not available')
  }
  try {
    const result = await window.go.main.App.Seek(addr, to)
    return result
  } catch (e) {
    throw new Error(`Seek failed: ${e}`)
  }
}

export async function setRate(addr, rate) {
  if (!wailsAvailable) {
    throw new Error('Wails runtime is not available')
  }
  try {
    const result = await window.go.main.App.SetRate(addr, rate)
    return result
  } catch (e) {
    throw new Error(`SetRate failed: ${e}`)
  }
}
