# Turn a binary file into a C header holding it as an unsigned char array.
# Usage: cmake -DIN=<file> -DOUT=<header> -DSYM=<identifier> -P bin2h.cmake
file(READ "${IN}" HEX_CONTENT HEX)
string(LENGTH "${HEX_CONTENT}" HEX_LEN)
math(EXPR BYTE_COUNT "${HEX_LEN} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," ARRAY_CONTENT "${HEX_CONTENT}")
file(WRITE "${OUT}" "// Generated by bin2h.cmake from ${IN}; do not edit.\n#pragma once\n#include <cstddef>\nstatic const unsigned char ${SYM}[] = {\n${ARRAY_CONTENT}\n};\nstatic const size_t ${SYM}_size = ${BYTE_COUNT};\n")
