// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyProject(arg1:string,arg2:string):Promise<string>;

export function Pause(arg1:string):Promise<string>;

export function Play(arg1:string,arg2:any):Promise<string>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function Seek(arg1:string,arg2:number):Promise<string>;

export function SetRate(arg1:string,arg2:number):Promise<string>;

export function Stop(arg1:string):Promise<string>;
