// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseRendererScreen(arg1:string):Promise<void>;

export function GetFileServerPort():Promise<number>;

export function GetInitError():Promise<string>;

export function GetRendererStatus(arg1:string):Promise<main.RendererStatus>;

export function LaunchRenderer(arg1:string,arg2:number,arg3:number):Promise<void>;

export function OpenRendererScreen(arg1:string,arg2:number,arg3:number):Promise<void>;

export function PickMediaFiles():Promise<Array<string>>;

export function PickMediaFolder():Promise<Array<string>>;

export function PushControl(arg1:string):Promise<void>;

export function PushSnapshot(arg1:string):Promise<void>;

export function PushTime(arg1:number):Promise<void>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function StopRenderer(arg1:string):Promise<void>;
