// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyProject(arg1, arg2) {
  return window['go']['main']['App']['ApplyProject'](arg1, arg2);
}

export function Pause(arg1) {
  return window['go']['main']['App']['Pause'](arg1);
}

export function Play(arg1, arg2) {
  return window['go']['main']['App']['Play'](arg1, arg2);
}

export function ReadFileBase64(arg1) {
  return window['go']['main']['App']['ReadFileBase64'](arg1);
}

export function Seek(arg1, arg2) {
  return window['go']['main']['App']['Seek'](arg1, arg2);
}

export function SetRate(arg1, arg2) {
  return window['go']['main']['App']['SetRate'](arg1, arg2);
}

export function Stop(arg1) {
  return window['go']['main']['App']['Stop'](arg1);
}
