// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileServerPort():Promise<number>;

export function ReadFileBase64(arg1:string):Promise<string>;
