#include "render_pipeline.h"
#include <cstdio>
#include <cstring>

// Pre-compiled shaders (generated by CMake/dxc)
#ifndef SHADERS_COMPILE_AT_RUNTIME
#include "quad_vs.h"
#include "effects_ps.h"
#endif

bool RenderPipeline::init(ID3D12Device* device) {
    // --- Root Signature ---
    // Slot 0: 32-bit constants for transform (8 floats = 32 bytes)
    // Slot 1: 32-bit constants for effects (12 floats = 48 bytes)
    // Slot 2: Descriptor table with 1 SRV (texture)
    // Static sampler: linear, clamp

    D3D12_ROOT_PARAMETER rootParams[3] = {};

    // Transform constants (b0)
    rootParams[0].ParameterType = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
    rootParams[0].Constants.ShaderRegister = 0;
    rootParams[0].Constants.Num32BitValues = sizeof(TransformCB) / 4;
    rootParams[0].ShaderVisibility = D3D12_SHADER_VISIBILITY_VERTEX;

    // Effects constants (b1)
    rootParams[1].ParameterType = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
    rootParams[1].Constants.ShaderRegister = 1;
    rootParams[1].Constants.Num32BitValues = sizeof(EffectsCB) / 4;
    rootParams[1].ShaderVisibility = D3D12_SHADER_VISIBILITY_PIXEL;

    // SRV table (t0)
    D3D12_DESCRIPTOR_RANGE srvRange = {};
    srvRange.RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_SRV;
    srvRange.NumDescriptors = 1;
    srvRange.BaseShaderRegister = 0;
    rootParams[2].ParameterType = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
    rootParams[2].DescriptorTable.NumDescriptorRanges = 1;
    rootParams[2].DescriptorTable.pDescriptorRanges = &srvRange;
    rootParams[2].ShaderVisibility = D3D12_SHADER_VISIBILITY_PIXEL;

    // Static sampler (s0)
    D3D12_STATIC_SAMPLER_DESC sampler = {};
    sampler.Filter = D3D12_FILTER_MIN_MAG_MIP_LINEAR;
    sampler.AddressU = D3D12_TEXTURE_ADDRESS_MODE_CLAMP;
    sampler.AddressV = D3D12_TEXTURE_ADDRESS_MODE_CLAMP;
    sampler.AddressW = D3D12_TEXTURE_ADDRESS_MODE_CLAMP;
    sampler.ShaderRegister = 0;
    sampler.ShaderVisibility = D3D12_SHADER_VISIBILITY_PIXEL;

    D3D12_ROOT_SIGNATURE_DESC rsDesc = {};
    rsDesc.NumParameters = 3;
    rsDesc.pParameters = rootParams;
    rsDesc.NumStaticSamplers = 1;
    rsDesc.pStaticSamplers = &sampler;
    rsDesc.Flags = D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT;

    ComPtr<ID3DBlob> sigBlob, errBlob;
    HRESULT hr = D3D12SerializeRootSignature(&rsDesc, D3D_ROOT_SIGNATURE_VERSION_1,
        &sigBlob, &errBlob);
    if (FAILED(hr)) {
        if (errBlob) fprintf(stderr, "[Pipeline] Root sig error: %s\n", (char*)errBlob->GetBufferPointer());
        return false;
    }
    hr = device->CreateRootSignature(0, sigBlob->GetBufferPointer(), sigBlob->GetBufferSize(),
        IID_PPV_ARGS(&m_rootSignature));
    if (FAILED(hr)) {
        fprintf(stderr, "[Pipeline] CreateRootSignature failed: 0x%08x\n", hr);
        return false;
    }

    // --- Shaders ---
    const void* vsData = nullptr;
    size_t vsSize = 0;
    const void* psData = nullptr;
    size_t psSize = 0;
    ComPtr<ID3DBlob> vsBlob, psBlob;

#ifdef SHADERS_COMPILE_AT_RUNTIME
    // Compile at runtime (fallback if dxc not found)
    // Not implemented yet — use pre-compiled shaders
    fprintf(stderr, "[Pipeline] Runtime shader compilation not implemented\n");
    return false;
#else
    vsData = g_quadVS;
    vsSize = sizeof(g_quadVS);
    psData = g_effectsPS;
    psSize = sizeof(g_effectsPS);
#endif

    // --- PSO ---
    D3D12_GRAPHICS_PIPELINE_STATE_DESC psoDesc = {};
    psoDesc.pRootSignature = m_rootSignature.Get();
    psoDesc.VS = { vsData, vsSize };
    psoDesc.PS = { psData, psSize };

    // Blend state: alpha blending
    psoDesc.BlendState.AlphaToCoverageEnable = FALSE;
    psoDesc.BlendState.IndependentBlendEnable = FALSE;
    psoDesc.BlendState.RenderTarget[0].BlendEnable = TRUE;
    psoDesc.BlendState.RenderTarget[0].SrcBlend = D3D12_BLEND_SRC_ALPHA;
    psoDesc.BlendState.RenderTarget[0].DestBlend = D3D12_BLEND_INV_SRC_ALPHA;
    psoDesc.BlendState.RenderTarget[0].BlendOp = D3D12_BLEND_OP_ADD;
    psoDesc.BlendState.RenderTarget[0].SrcBlendAlpha = D3D12_BLEND_ONE;
    psoDesc.BlendState.RenderTarget[0].DestBlendAlpha = D3D12_BLEND_INV_SRC_ALPHA;
    psoDesc.BlendState.RenderTarget[0].BlendOpAlpha = D3D12_BLEND_OP_ADD;
    psoDesc.BlendState.RenderTarget[0].RenderTargetWriteMask = D3D12_COLOR_WRITE_ENABLE_ALL;

    // Rasterizer
    psoDesc.RasterizerState.FillMode = D3D12_FILL_MODE_SOLID;
    psoDesc.RasterizerState.CullMode = D3D12_CULL_MODE_NONE;
    psoDesc.RasterizerState.DepthClipEnable = TRUE;

    // No depth
    psoDesc.DepthStencilState.DepthEnable = FALSE;
    psoDesc.DepthStencilState.StencilEnable = FALSE;

    // Primitive topology
    psoDesc.PrimitiveTopologyType = D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE;

    // Render target
    psoDesc.NumRenderTargets = 1;
    psoDesc.RTVFormats[0] = DXGI_FORMAT_R8G8B8A8_UNORM;
    psoDesc.SampleDesc.Count = 1;
    psoDesc.SampleMask = UINT_MAX;

    hr = device->CreateGraphicsPipelineState(&psoDesc, IID_PPV_ARGS(&m_pso));
    if (FAILED(hr)) {
        fprintf(stderr, "[Pipeline] CreateGraphicsPipelineState failed: 0x%08x\n", hr);
        return false;
    }

    m_initialized = true;
    printf("[Pipeline] Initialized with textured quad PSO\n");
    return true;
}

void RenderPipeline::clearScreen(ID3D12GraphicsCommandList* cmdList,
                                  D3D12_CPU_DESCRIPTOR_HANDLE rtv,
                                  int width, int height,
                                  float r, float g, float b, float a) {
    float clearColor[] = {r, g, b, a};
    cmdList->ClearRenderTargetView(rtv, clearColor, 0, nullptr);

    D3D12_VIEWPORT vp = {0.0f, 0.0f, (float)width, (float)height, 0.0f, 1.0f};
    cmdList->RSSetViewports(1, &vp);

    D3D12_RECT scissor = {0, 0, (LONG)width, (LONG)height};
    cmdList->RSSetScissorRects(1, &scissor);

    cmdList->OMSetRenderTargets(1, &rtv, FALSE, nullptr);
}

void RenderPipeline::bindHeap(ID3D12GraphicsCommandList* cmdList, ID3D12DescriptorHeap* srvHeap) {
    if (!m_initialized) return;
    cmdList->SetPipelineState(m_pso.Get());
    cmdList->SetGraphicsRootSignature(m_rootSignature.Get());
    ID3D12DescriptorHeap* heaps[] = { srvHeap };
    cmdList->SetDescriptorHeaps(1, heaps);
    cmdList->IASetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP);
}

void RenderPipeline::drawQuad(ID3D12GraphicsCommandList* cmdList,
                               const TransformCB& transform,
                               const EffectsCB& effects,
                               D3D12_GPU_DESCRIPTOR_HANDLE textureSrv) {
    if (!m_initialized) return;
    cmdList->SetGraphicsRoot32BitConstants(0, sizeof(TransformCB) / 4, &transform, 0);
    cmdList->SetGraphicsRoot32BitConstants(1, sizeof(EffectsCB) / 4, &effects, 0);
    cmdList->SetGraphicsRootDescriptorTable(2, textureSrv);
    cmdList->DrawInstanced(4, 1, 0, 0); // 4 vertices for triangle strip quad
}
