// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseAllRendererScreens closes every renderer window, stops every renderer
 * this editor launched, and kills renderer processes left behind by earlier
 * editor instances. It returns how many orphans it killed, so the UI can say.
 * @returns {$CancellablePromise<number>}
 */
export function CloseAllRendererScreens() {
    return $Call.ByID(2225275622);
}

/**
 * CloseRendererScreen sends a screen-close event and stops the renderer.
 * @param {string} screenID
 * @returns {$CancellablePromise<void>}
 */
export function CloseRendererScreen(screenID) {
    return $Call.ByID(3354850320, screenID);
}

/**
 * FileExists reports whether a local media file is still on disk.
 * 
 * The Media Bin needs to tell "the file moved" apart from "the thumbnail
 * failed to decode"; both used to render as the same grey placeholder. Goes
 * through the same path validation as the file server, so it cannot be used
 * to probe arbitrary locations.
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function FileExists(path) {
    return $Call.ByID(2577714203, path);
}

/**
 * GetDocumentContents returns the canonical JSON of the open show, already
 * validated and migrated.
 * @returns {$CancellablePromise<string>}
 */
export function GetDocumentContents() {
    return $Call.ByID(1048337760);
}

/**
 * GetDocumentState reports the open show. The editor calls this once at
 * startup and then follows the document:state event.
 * @returns {$CancellablePromise<$models.DocumentState>}
 */
export function GetDocumentState() {
    return $Call.ByID(2039234095).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetFileServerPort returns the sidecar server port for the frontend.
 * @returns {$CancellablePromise<number>}
 */
export function GetFileServerPort() {
    return $Call.ByID(461345393);
}

/**
 * GetFileServerToken returns the session token every sidecar request for
 * local media or the event stream must carry.
 * @returns {$CancellablePromise<string>}
 */
export function GetFileServerToken() {
    return $Call.ByID(1383479731);
}

/**
 * GetInitError returns any initialization error (empty string if all OK).
 * @returns {$CancellablePromise<string>}
 */
export function GetInitError() {
    return $Call.ByID(484225613);
}

/**
 * GetRecentShows lists recently opened or saved shows, most recent first.
 * @returns {$CancellablePromise<string[]>}
 */
export function GetRecentShows() {
    return $Call.ByID(354595858).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetRendererStatus returns the current status of a renderer for a screen.
 * @param {string} screenID
 * @returns {$CancellablePromise<$models.RendererStatus>}
 */
export function GetRendererStatus(screenID) {
    return $Call.ByID(3739970530, screenID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetTransportState reports position and run state without changing them.
 * The editor calls this once at startup and then follows transport:state.
 * @returns {$CancellablePromise<$models.TransportState>}
 */
export function GetTransportState() {
    return $Call.ByID(1678271201).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * LaunchRenderer starts a native renderer process for a screen.
 * @param {string} screenID
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<void>}
 */
export function LaunchRenderer(screenID, width, height) {
    return $Call.ByID(1648992229, screenID, width, height);
}

/**
 * NewShow replaces the open document with an empty one.
 * 
 * The caller is responsible for asking about unsaved work first: only the UI
 * can put that question to the operator, and only it knows whether the answer
 * was cancel.
 * @returns {$CancellablePromise<$models.OpenedDocument>}
 */
export function NewShow() {
    return $Call.ByID(406399808).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * OpenRendererScreen launches a renderer process and sends a screen-open SSE event.
 * @param {string} screenID
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<void>}
 */
export function OpenRendererScreen(screenID, width, height) {
    return $Call.ByID(4084424734, screenID, width, height);
}

/**
 * OpenRendererScreenAt is OpenRendererScreen with a desktop position: the
 * window's client area goes at (x, y) in physical virtual-screen pixels, and
 * borderless drops the frame so it can cover a display exactly.
 * @param {string} screenID
 * @param {number} width
 * @param {number} height
 * @param {number} x
 * @param {number} y
 * @param {boolean} borderless
 * @returns {$CancellablePromise<void>}
 */
export function OpenRendererScreenAt(screenID, width, height, x, y, borderless) {
    return $Call.ByID(486438651, screenID, width, height, x, y, borderless);
}

/**
 * OpenShow asks for a file and loads it.
 * @returns {$CancellablePromise<$models.OpenedDocument>}
 */
export function OpenShow() {
    return $Call.ByID(2918353848).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * OpenShowPath loads a specific file, for the recent-files menu and for a
 * path handed to the application on its command line.
 * @param {string} path
 * @returns {$CancellablePromise<$models.OpenedDocument>}
 */
export function OpenShowPath(path) {
    return $Call.ByID(1979109199, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * PickMediaFiles opens a native file dialog and returns absolute paths.
 * This avoids blob: URIs which don't work cross-origin in display windows.
 * @returns {$CancellablePromise<string[]>}
 */
export function PickMediaFiles() {
    return $Call.ByID(4150223347).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * PickMediaFolder opens a native directory dialog and returns absolute paths of all files in it.
 * @returns {$CancellablePromise<string[]>}
 */
export function PickMediaFolder() {
    return $Call.ByID(3227316560).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * QuitConfirmed ends the application after the frontend has confirmed that
 * unsaved work may be discarded (or found there was none).
 * @returns {$CancellablePromise<void>}
 */
export function QuitConfirmed() {
    return $Call.ByID(1997179935);
}

/**
 * ReadFileBase64 delegates to the FileService for Wails binding.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFileBase64(path) {
    return $Call.ByID(467254620, path);
}

/**
 * RenameShow changes the show's own name, independently of its file name.
 * @param {string} name
 * @returns {$CancellablePromise<$models.DocumentState>}
 */
export function RenameShow(name) {
    return $Call.ByID(3579588782, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * RevealInExplorer opens the OS file browser with the file selected.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function RevealInExplorer(path) {
    return $Call.ByID(4223801352, path);
}

/**
 * SaveShow writes the open show back to its own file, falling through to
 * Save As when it has never been saved.
 * @returns {$CancellablePromise<$models.SavedDocument>}
 */
export function SaveShow() {
    return $Call.ByID(1419632521).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * SaveShowAs asks for a location and writes the open show there.
 * @returns {$CancellablePromise<$models.SavedDocument>}
 */
export function SaveShowAs() {
    return $Call.ByID(871748145).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * StopRenderer stops the renderer process for a screen.
 * @param {string} screenID
 * @returns {$CancellablePromise<void>}
 */
export function StopRenderer(screenID) {
    return $Call.ByID(2537136262, screenID);
}

/**
 * TransportPause holds the playhead where it is.
 * @returns {$CancellablePromise<$models.TransportState>}
 */
export function TransportPause() {
    return $Call.ByID(3349903388).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * TransportPlay starts or resumes playback.
 * @returns {$CancellablePromise<$models.TransportState>}
 */
export function TransportPlay() {
    return $Call.ByID(3819555956).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * TransportSeek moves the playhead, keeping the current run state.
 * @param {number} seconds
 * @returns {$CancellablePromise<$models.TransportState>}
 */
export function TransportSeek(seconds) {
    return $Call.ByID(3075920242, seconds).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * TransportSetRate changes playback speed, keeping the current position.
 * @param {number} rate
 * @returns {$CancellablePromise<$models.TransportState>}
 */
export function TransportSetRate(rate) {
    return $Call.ByID(3982477624, rate).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * TransportStop halts playback and rewinds to the beginning.
 * @returns {$CancellablePromise<$models.TransportState>}
 */
export function TransportStop() {
    return $Call.ByID(1557082450).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * UpdateShow records an edited document and forwards it to every renderer.
 * 
 * One call for what used to be two independent paths: a PushSnapshot that
 * fed the outputs and a React reference comparison that decided the title bar
 * dot. They could disagree, and after an undo they did.
 * @param {string} contents
 * @returns {$CancellablePromise<$models.DocumentState>}
 */
export function UpdateShow(contents) {
    return $Call.ByID(1877453301, contents).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.DocumentState.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $models.RendererStatus.createFrom;
const $$createType3 = $models.TransportState.createFrom;
const $$createType4 = $models.OpenedDocument.createFrom;
const $$createType5 = $models.SavedDocument.createFrom;
