// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseRendererScreen sends a screen-close event and stops the renderer.
 * @param {string} screenID
 * @returns {$CancellablePromise<void>}
 */
export function CloseRendererScreen(screenID) {
    return $Call.ByID(3354850320, screenID);
}

/**
 * FileExists reports whether a local media file is still on disk.
 * 
 * The Media Bin needs to tell "the file moved" apart from "the thumbnail
 * failed to decode"; both used to render as the same grey placeholder. Goes
 * through the same path validation as the file server, so it cannot be used
 * to probe arbitrary locations.
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function FileExists(path) {
    return $Call.ByID(2577714203, path);
}

/**
 * GetFileServerPort returns the sidecar server port for the frontend.
 * @returns {$CancellablePromise<number>}
 */
export function GetFileServerPort() {
    return $Call.ByID(461345393);
}

/**
 * GetInitError returns any initialization error (empty string if all OK).
 * @returns {$CancellablePromise<string>}
 */
export function GetInitError() {
    return $Call.ByID(484225613);
}

/**
 * GetRendererStatus returns the current status of a renderer for a screen.
 * @param {string} screenID
 * @returns {$CancellablePromise<$models.RendererStatus>}
 */
export function GetRendererStatus(screenID) {
    return $Call.ByID(3739970530, screenID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * LaunchRenderer starts a native renderer process for a screen.
 * @param {string} screenID
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<void>}
 */
export function LaunchRenderer(screenID, width, height) {
    return $Call.ByID(1648992229, screenID, width, height);
}

/**
 * OpenRendererScreen launches a renderer process and sends a screen-open SSE event.
 * @param {string} screenID
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<void>}
 */
export function OpenRendererScreen(screenID, width, height) {
    return $Call.ByID(4084424734, screenID, width, height);
}

/**
 * PickMediaFiles opens a native file dialog and returns absolute paths.
 * This avoids blob: URIs which don't work cross-origin in display windows.
 * @returns {$CancellablePromise<string[]>}
 */
export function PickMediaFiles() {
    return $Call.ByID(4150223347).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * PickMediaFolder opens a native directory dialog and returns absolute paths of all files in it.
 * @returns {$CancellablePromise<string[]>}
 */
export function PickMediaFolder() {
    return $Call.ByID(3227316560).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * PushControl sends a transport command to all connected renderers.
 * @param {string} command
 * @returns {$CancellablePromise<void>}
 */
export function PushControl(command) {
    return $Call.ByID(3459093070, command);
}

/**
 * PushSnapshot sends the full project state to all connected renderers.
 * @param {string} projectJSON
 * @returns {$CancellablePromise<void>}
 */
export function PushSnapshot(projectJSON) {
    return $Call.ByID(2495583325, projectJSON);
}

/**
 * PushTime sends the current playback time to all connected renderers.
 * @param {number} t
 * @returns {$CancellablePromise<void>}
 */
export function PushTime(t) {
    return $Call.ByID(983995156, t);
}

/**
 * ReadFileBase64 delegates to the FileService for Wails binding.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFileBase64(path) {
    return $Call.ByID(467254620, path);
}

/**
 * RevealInExplorer opens the OS file browser with the file selected.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function RevealInExplorer(path) {
    return $Call.ByID(4223801352, path);
}

/**
 * StopRenderer stops the renderer process for a screen.
 * @param {string} screenID
 * @returns {$CancellablePromise<void>}
 */
export function StopRenderer(screenID) {
    return $Call.ByID(2537136262, screenID);
}

// Private type creation functions
const $$createType0 = $models.RendererStatus.createFrom;
const $$createType1 = $Create.Array($Create.Any);
