// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * RendererStatus is returned to the frontend via Wails binding.
 */
export class RendererStatus {
    /**
     * Creates a new RendererStatus instance.
     * @param {Partial<RendererStatus>} [$$source = {}] - The source object to create the RendererStatus.
     */
    constructor($$source = {}) {
        if (!("screenId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["screenId"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * "launching", "ready", "error", "stopped"
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("fps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fps"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RendererStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RendererStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RendererStatus(/** @type {Partial<RendererStatus>} */($$parsedSource));
    }
}
